# Use Astral's official Python 3.14 image with uv pre-installed
FROM ghcr.io/astral-sh/uv:python3.14-trixie-slim

WORKDIR /app

# Enable bytecode compilation and use copy mode for caching optimization
ENV UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy

# 1. Copy only dependency files first to leverage Docker layer caching
COPY pyproject.toml uv.lock ./

# 2. Install dependencies (frozen ensures lockfile is respected, no-dev skips testing tools)
RUN uv sync --frozen --no-dev --no-install-project

# 3. Copy the rest of your application code
COPY . /app

# Set up non-root user for security and adjust permissions
RUN useradd -u 1000 appuser && chown -R appuser /app
USER appuser

EXPOSE 8080

# Run the app using the virtual environment python generated by uv
CMD [".venv/bin/python", "app.py"]
